{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/exceptions\/appcontextlost\/reason"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/AppContextLost\/reason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"String describing the reason of the exception."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"reason","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:15ExpoModulesCore10ExceptionsV14AppContextLostC6reasonSSvp","modules":[{"name":"ExpoModulesCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/AppContextLost"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions":{"role":"symbol","title":"Exceptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Exceptions"}],"abstract":[{"type":"text","text":"A group of the most common exceptions that might be necessary for modules."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Exceptions"}],"url":"\/documentation\/expomodulescore\/exceptions"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/AppContextLost/reason":{"role":"symbol","title":"reason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"String describing the reason of the exception."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/AppContextLost\/reason","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/exceptions\/appcontextlost\/reason"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/AppContextLost":{"role":"symbol","title":"Exceptions.AppContextLost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppContextLost"}],"abstract":[{"type":"text","text":"The Expo app context is no longer available."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/AppContextLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppContextLost"}],"url":"\/documentation\/expomodulescore\/exceptions\/appcontextlost"}}}